nu_urc:
  joint_state_publisher:
    type: joint_state_controller/JointStateController
    publish_rate: 30

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: [p: 0.00, i: 0.00, d: 0.00]
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: [p: 0.00, i: 0.00, d: 0.00]
